services:
  cve-2024-53900:
    build: .
    container_name: cve-2024-53900
    environment:
      - AIKIDO_BLOCK=true
      - AIKIDO_DEBUG=true
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
