services:
  cve-2016-1000225:
    build: .
    container_name: cve-2016-1000225
    environment:
      - AIKIDO_BLOCK=true
      - AIKIDO_DEBUG=true
    depends_on:
      - postgis
  postgis:
    image: postgis/postgis:13-3.5
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
      POSTGRES_USER: test
    ports:
      - "5433:5432"
