services:
  cve-2016-20018:
    build: .
    container_name: cve-2016-20018
    environment:
      - AIKIDO_BLOCK=true
      - AIKIDO_DEBUG=true
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
